# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logRegApp', '0004_auto_20170421_1402'),
        ('travelBudApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='users',
            field=models.ManyToManyField(related_name='trips', to='logRegApp.User'),
        ),
    ]
