# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logRegApp', '0004_auto_20170421_1402'),
        ('travelBudApp', '0002_trip_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='users',
        ),
        migrations.AddField(
            model_name='trip',
            name='joiners',
            field=models.ManyToManyField(related_name='join_user', to='logRegApp.User'),
        ),
        migrations.AddField(
            model_name='trip',
            name='planner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='plan_user', to='logRegApp.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_start',
            field=models.DateTimeField(),
        ),
    ]
