# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelBudApp', '0003_auto_20170424_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travel_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_start',
            field=models.DateField(),
        ),
    ]
